import type { Metadata } from 'next';

import '@/styles/globals.css';

import { StoreProvider } from '@/app/StoreProvider';
import { mainNavConfig } from '@/config';

import { Footer } from '@/components/Footer';
import { Header } from '@/components/Header';
import { Layout } from '@/components/Layout';
import { MainNav } from '@/components/MainNav';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-primary text-gray-100">
        <Header>
          <MainNav items={ mainNavConfig }/>
        </Header>
        <StoreProvider>
          <Layout>
            <div className='py-20'>
              {children}
            </div>
          </Layout>
        </StoreProvider>
        <Footer />
      </body>
    </html>
  );
}
